version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: django
    versions:
    - ">= 3.a, < 4"
  - dependency-name: django
    versions:
    - 2.2.17
    - 2.2.19
  - dependency-name: autopep8
    versions:
    - 1.5.4
    - 1.5.5
  - dependency-name: pytz
    versions:
    - "2020.5"
    - "2021.1"
  - dependency-name: sqlparse
    versions:
    - 0.4.1
