# Generated by Django 2.2.6 on 2019-10-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50, verbose_name='歌曲名稱')),
                ('song_singer', models.CharField(max_length=50, verbose_name='歌手')),
                ('submitter', models.CharField(max_length=10, verbose_name='提交者')),
                ('submitterID', models.CharField(max_length=9, verbose_name='提交者學號')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交時間')),
            ],
            options={
                'verbose_name': '報名資料',
                'verbose_name_plural': '報名資料',
            },
        ),
    ]
